version: 4.0.0.{build}

environment:
  CLCACHE_VERSION: 4.0.0

  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    # NOTE: PyInstaller does not work with Python 3.6

    # NOTE: PyInstaller with Python 3.5 is not running on Windows Vista, giving the following error:
    # Error loading Python DLL: C:\ProgramData\chocolatey\lib\clcache\clcache-4.0.0\python35.dll (error code 1114)
    # Changing the default to be Python 3.4.
    # More information about the problem here (other possible workarounds):
    #   https://www.ddo.com/forums/showthread.php/436296-DDO-ML-an-ultrafast-lightweight-DDO-launcher/page14
    # Possibly related issues:
    #   https://github.com/pyinstaller/pyinstaller/issues/1566
    #   https://github.com/pyinstaller/pyinstaller/issues/2170
    
    # - PYTHON: "C:\\Python35-x64"
    #   PYTHON_VERSION: "3.5.x" # currently 3.5.2
    #   PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x" # currently 3.4.4
      PYTHON_ARCH: "64"

platform:
  - x64

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - "pip install -r dev-requirements.txt"
  
  # Update submodules
  # - git submodule update --init --recursive
  
  # Download and unpack source into "clcache" directory
  - curl -sSL https://codeload.github.com/frerich/clcache/zip/v%CLCACHE_VERSION% -o clcache-src-%CLCACHE_VERSION%.zip
  - 7z x -y clcache-src-%CLCACHE_VERSION%.zip >NUL
  - move clcache-%CLCACHE_VERSION% clcache

build_script:
  # Build the compiled extension
  - cd clcache
  - pyinstaller clcache.py
  - cd ..
  - move clcache\dist\clcache clcache-%CLCACHE_VERSION%
  
  # Build the Chocolatey package
  - sed -i "s/{VERSION}/%CLCACHE_VERSION%/g" clcache.nuspec
  - choco pack

test_script:
  # Test the compiled extension
  - cd clcache-%CLCACHE_VERSION%
  - clcache.exe --help
  - cd ..
  
  # Test the chocolatey package
  - choco install -v -d clcache.%CLCACHE_VERSION%.nupkg
  - clcache --help
  - where clcache

on_success:
  - "echo Branch: %APPVEYOR_REPO_BRANCH%"
  - "echo Pull Request: %APPVEYOR_PULL_REQUEST_NUMBER%"
  - "echo Tag: %APPVEYOR_REPO_TAG_NAME%"
  - cd clcache-%CLCACHE_VERSION%
  - 7z a -y clcache-%CLCACHE_VERSION%.zip
  - move clcache-%CLCACHE_VERSION%.zip ..
  - cd ..
  - if "%APPVEYOR_REPO_BRANCH%"=="master" if "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" if not "%APPVEYOR_REPO_TAG_NAME%"=="" set PUBLISH=1
  - sha256sum clcache.%CLCACHE_VERSION%.nupkg clcache-%CLCACHE_VERSION%.zip
  - sha256sum clcache.%CLCACHE_VERSION%.nupkg clcache-%CLCACHE_VERSION%.zip > SHA256SUM
  - if "%PUBLISH%"=="1" appveyor PushArtifact clcache.%CLCACHE_VERSION%.nupkg
  - if "%PUBLISH%"=="1" appveyor PushArtifact clcache-%CLCACHE_VERSION%.zip
  - if "%PUBLISH%"=="1" appveyor PushArtifact SHA256SUM
